version: '3.8'

services:
  weather_app:
    build: .
    command: ["./entrypoint.sh"]
    volumes:
      - .:/usr/app
    ports:
      - "8000:8000"
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
